# Pengaturan Waktu Daily Reset (WIB / Indonesia)
# Jika diset 6, maka jam 6 pagi WIB hadiah baru bisa diklaim (Jam 11 malam Abidjan).
daily-reset-hour-wib: 6

# Jam Minecraft (0-24000)
moon-effect-start: 13000
moon-effect-end: 22500

# Skill Settings
lunar-sweep-cooldown: 5
lunar-sweep-chance: 0.2

# Messages
welcome-message: "&6&l[!] &eWelcome to the &6Golden Moon &eEvent!"
daily-claimed: "&e&l[Daily] &fYou reached &bDay %day%&f progress!"
skill-cooldown: "&c[!] Skill is on cooldown: %time%s"
limited-item-received: "&b&l[!] AMAZING! You received the &6Golden Crescent Blade!"
