welcome-message: "&6&l[!] &eWelcome to the &6Golden Moon &eEvent!"
event-ended: "&c[!] The event has concluded. See you next year!"
daily-claimed: "&e&l[Daily] &fYou reached &bDay %day%&f progress!"
quest-success: "&a&l[Quest] &fTakjil shared! Here is your reward."
receive-takjil: "&6&l[Ramadhan] &fYou received a gift from &e%player%&f!"
limited-item-received: "&b&l[!] UNBELIEVABLE! You received the &6Golden Crescent Blade!"

